### ISSUE TITLE
Moving .gleam doesn't remove old .erl files 

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/mix_gleam#24]
```
$ ls build/dev/erlang/hello/build/
hello.erl  hello.gleam_module
$ mkdir src/hey && mv src/hello.gleam src/hey
$ mix compile
Compiling 1 file (.gleam)
Compiling 1 file (.erl)
Generated hello app
$ ls build/dev/erlang/hello/build/
hello.erl  hello.gleam_module  hey@hello.erl  hey@hello.gleam_module
```

The `hello.erl`  and `hello.gleam_module` files should no longer be there

**Comment by tynanbe** [comment]
We might need to clear the project subdir in `build/dev/erlang` on every compile to cover this.

Otherwise, we could potentially leave it to users to run `gleam clean` in these situations, but that's likely not ideal.

@lpil does this seem like something `gleam compile-package` should handle? I'm thinking maybe not.

**Comment by lpil** [comment]
It should not, no. That'd the role of a build tool.

**Comment by tynanbe** [comment]
Closed by https://github.com/gleam-lang/mix_gleam/commit/04d0d7a1dbd23cb20fd040e6f4c4e2de7a1216e8
